version: "3.5"
services:

  db:
    image: postgis/postgis:13-3.0
    volumes:
      - /home/quantum/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sip_db
      - POSTGRES_USER=sip
      - POSTGRES_PASSWORD=Foo0roo0
    networks:
      - sip

  webapplication:
    build:
      context: ./webapplication
      dockerfile: prod.Dockerfile
    volumes:
      - ./webapplication:/code
      - ../data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DJANGO_SETTINGS_MODULE=sip.settings-ukraine
      - POSTGRES_DB=sip_db
      - POSTGRES_USER=sip
      - POSTGRES_PASSWORD=Foo0roo0
    command: /bin/bash -c "exec invoke run-ukraine"
    depends_on:
      - db
    networks:
      - sip

  webserver:
    build:
      context: ./
      dockerfile: ./webserver/prod.Dockerfile
      args:
        - REACT_APP_HOTJAR_ID=${REACT_APP_HOTJAR_ID}
        - REACT_APP_HOTJAR_SV=${REACT_APP_HOTJAR_SV}
        - REACT_APP_EMAILJS_SERVICE_ID=${REACT_APP_EMAILJS_SERVICE_ID}
        - REACT_APP_EMAILJS_TEMPLATE_ID=${REACT_APP_EMAILJS_TEMPLATE_ID}
        - REACT_APP_EMAILJS_USER_ID=${REACT_APP_EMAILJS_USER_ID}
        - REACT_APP_AUTOLOGIN=${REACT_APP_AUTOLOGIN}
        - REACT_APP_AUTOPASSWORD=${REACT_APP_AUTOPASSWORD}
    volumes:
      - ../data:/data
      - /etc/letsencrypt:/etc/letsencrypt
    expose:
      - 80
      - 443
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - webapplication
    networks:
      - sip
    env_file:
      - /home/ec2-user/webserver.env

networks:
  sip:
